---
# geerling.security
security_sudoers_passwordless: ['ubuntu']

# Install Kubernetes packages.
kubernetes_packages:
  - name: kubectl
    state: present

kubernetes_apt_release_channel: main
# Note that xenial repo is used for all Debian derivatives at this time.
kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_apt_release_channel }}"
kubernetes_apt_ignore_key_error: false

kubernetes_version: '1.27'

# Install Cloudflare SSL client tool

cfssl_package_version: 'v1.6.4'
cfssl_binary: 'cfssl_1.6.4_linux_arm64'
cfssljson_binary: 'cfssljson_1.6.4_linux_arm64'
